### ISSUE TITLE
创建一个新的监控项目 提示等待监控器 在监控器列表当中为空 

### ISSUE THREAD

**Issue by yuluoqingcheng** [mangenotwork/website-monitor#3]
创建一个新的监控项目 提示等待监控器 在监控器列表当中为空  如何添加监控器
![1710322208188](https://github.com/mangenotwork/website-monitor/assets/52369645/9d234576-7ae5-4e0d-8ba2-a56ab0386244)
![image](https://github.com/mangenotwork/website-monitor/assets/52369645/a599e84e-1f18-4a9f-ad07-9b14279fd407)

**Comment by mangenotwork** [comment]
启动  monitor
配置中需要设置 master地址, 与mater一一对应的 connCode connSecret
```
# 与master通讯的udp地址
master: 192.168.3.86:18889
# master接口地址，获取相关数据
masterHTTP: http://192.168.3.86:18888
# client name 最多7个字符
clientName: node2
connCode: qwert
connSecret: abc123!@
```

**Comment by yuluoqingcheng** [comment]
谢谢

**Comment by yuluoqingcheng** [comment]
主要不知道如何添加监控器 现在不知道如何解决监控器
